#!python
# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

configfile: "../snakemake_config/config_test.json"

rule_dir = "../snakemake_rules/"

include:
  rule_dir + "picard_sort.rule"
include:
  rule_dir + "bwa_samse.rule"
include:
  rule_dir + "bwa_aln.rule"
include:
  rule_dir + "wisecondor_test.rule"

rule all:
  input:
      expand(config["path"]["wcresult"] + "{sample}.report", sample = config["sampleID"])

